const TITULAR_AMOUNT = 1;
const LAST_NEWS_AMOUNT = 8;
const INITIAL_NEWS_AMOUNT = 5;
const LOAD_MORE_NEWS_AMOUNT = 5;

export {
  TITULAR_AMOUNT,
  LAST_NEWS_AMOUNT,
  INITIAL_NEWS_AMOUNT,
  LOAD_MORE_NEWS_AMOUNT,
};
