const routes = {
  'Quienes somos': '/quienes-somos',
  Historia: '/quienes-somos/historia',
  Identidad: '/quienes-somos/identidad',
  'Evangelización marista': '/quienes-somos/evangelizacion-marista',
  'Proyecto educativo institucional': '/quienes-somos/pei',
  'Sistema institucional de evaluación':
    '/quienes-somos/sistema-evaluacion-institucional',
  'Proyecto ecológico': '/quienes-somos/proyecto-ecologico',
  'Manual de convivencia': '/quienes-somos/manual-convivencia',
  Protocolos: '/quienes-somos/protocolos',
  'Tratamiento de datos': '/quienes-somos/tratamiento-datos',
  Admisiones: '/admisiones',
  'Pasos del proceso': '/admisiones/pasos',
  Políticas: '/admisiones/politicas',
  'Información complementaria': '/admisiones/info',
  Noticias: '/noticias',
  Boletines: '/noticias/boletines',
  'Desde el cuarto piso': '/noticias/cuarto-piso',
  Estudiantes: '/estudiantes',
  'Campus virtual': '/estudiantes/campus-virtual',
  'Calendario académico': '/estudiantes/calendario',
  'Recursos académicos': '/estudiantes/recursos',
  Biblioteca: '/estudiantes/biblioteca',
  Padres: '/padres',
  Circulares: '/padres/circulares',
  'Contacto docente': '/padres/contacto-docente',
  'Consejo de padres': '/padres/consejo-padres',
  Rutas: '/padres/rutas',
  'Útiles escolares': '/padres/utiles',
  Asofamilia: '/asofamilia',
  Contacto: '/contacto',
  PQRSF: '/contacto/pqrsf',
  'Rutas de atención y denuncia': '/contacto/rutas-atencion',
  Portales: '/portales',
  'Correo marista':
    'https://login.microsoftonline.com/common/oauth2/authorize?client_id=4345a7b9-9a63-4910-a426-35363201d503&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dc7xkDH7-dEGtEiVnIz4pEHCzXjXp-nv-cCrt1166A4S-BSQMMAOGGzP5K-7PblfXn9nE-Oglg32QFqkGeokoFPaAHWp1kup8KRuxXi9kpLAu8DBxua3zuYPzyKRYYE2l&nonce=636915458618517671.YzllMjkwNTAtODAyZS00NzdmLWJhZTUtMmM5ODRhMzIyMTc1YmVhMDJlNWItYzJlNi00ZTRjLWIxOWItYmFiMDE3OThjNjNl&redirect_uri=https%3a%2f%2fwww.office.com%2f&ui_locales=es-CO&mkt=es-CO&client-request-id=2ea9c851-f840-45d5-a4a0-1f3bdd62b677',
  'Encuestas maristas': 'https://encuestas.fmsnor.org/bogota/',
  'Indicadores maristas':
    'https://encuestas.fmsnor.org/indicadores/appsc_Login/',
  Pagos:
    'https://www.e-collect.com/customers/Plus/ColegioChampagnatBogotaPagosPlus.htm',
  'Portal docente': 'https://portal.fmsnor.org/',
  SGC: 'https://documentacion.fmsnor.org/bogota/login/',
};

export { routes };
